import { PortfolioItem } from '~/app/types/content/PortfolioItem';

export const portfolio: PortfolioItem[] = [
  {
    id: 'start-v4',
    name: 'Start v4',
    badges: ['Angular', 'TypeScript', 'Vue', 'Microfrontend'],
    image: 'https://stuff.p-kin.com/pf-thumbs/startv4.jpg',
  },
  {
    id: 'pk-central-v2',
    name: 'PK-Central v2',
    badges: ['Python', 'FastAPI', 'AI Powered', 'MongoDB', 'Docker'],
    image: 'https://stuff.p-kin.com/pf-thumbs/pk-central-v2.jpg',
  },
  {
    id: 'tripz',
    name: 'Tripz',
    badges: ['React', 'TypeScript', 'Leaflet Map', 'Mantine UI'],
    image: 'https://stuff.p-kin.com/pf-thumbs/tripz.jpg',
  },
  {
    id: 'frazewise',
    name: 'FrazeWise',
    badges: ['Angular', 'TypeScript', 'AI Powered', 'Node.js', 'MongoDB'],
    image: 'https://stuff.p-kin.com/pf-thumbs/frazewise.jpg',
  },
  {
    id: 'servlogs',
    name: 'ServLogs',
    badges: ['Python', 'Websockets', 'Docker', 'Vanilla JS'],
    image: 'https://stuff.p-kin.com/pf-thumbs/servlogs.jpg',
  },
  {
    id: 'strava-routes',
    name: 'Strava Routes',
    badges: ['Python', 'Vanilla JS', 'MongoDB', 'Leaflet Map'],
    image: 'https://stuff.p-kin.com/pf-thumbs/strava-routes.jpg',
  },
  {
    id: 'pit-cli',
    badges: ['TypeScript', 'CLI', 'Node.js'],
    name: 'Pit CLI',
    image: 'https://stuff.p-kin.com/pf-thumbs/pit-cli.jpg',
  },
  {
    id: 'pkincom-v3',
    name: 'P-Kin.com V3',
    badges: ['Angular', 'TypeScript'],
    image: 'https://stuff.p-kin.com/pf-thumbs/pkincom-v3.jpg',
  },
  {
    id: 'velolyze',
    name: 'Velolyze',
    badges: ['Angular', 'TypeScript', 'PrimeNG', 'Firebase'],
    image: 'https://stuff.p-kin.com/pf-thumbs/velolyze.jpg',
  },
  {
    id: 'pk-central',
    name: 'PK-Central',
    badges: ['Node.js', 'TypeScript', 'API', 'MongoDB', 'Docker'],
    image: 'https://stuff.p-kin.com/pf-thumbs/pk-central.jpg',
  },
  {
    id: 'map-of-things',
    name: 'Map of Things',
    badges: ['React', 'TypeScript', 'OpenSeaDragon', 'CI/CD'],
    image: 'https://stuff.p-kin.com/pf-thumbs/map-of-things.jpg',
  },
  {
    id: 'pk-start',
    name: 'PK-Start (v3)',
    badges: [
      'Full Stack',
      'Angular',
      'Node.js',
      'NestJS',
      'MongoDB',
      'Material',
      'TypeScript',
      'CI/CD',
      'Docker',
    ],
    image: 'https://stuff.p-kin.com/pf-thumbs/pkstart.jpg',
  },
  {
    id: 'mongo-nest-angular-auth',
    name: 'MongoDB + NestJS + Angular Auth',
    badges: ['Full Stack', 'Angular', 'TypeScript', 'Material', 'Node.js', 'NestJS', 'MongoDB'],
    image: 'https://stuff.p-kin.com/pf-thumbs/tripplanner-login.png',
  },
  {
    id: 'notes-native',
    name: 'Notes Native',
    badges: ['Mobile', 'Android', 'Flutter', 'Dart', 'Firebase'],
    image: 'https://stuff.p-kin.com/pf-thumbs/notes-flutter.jpg',
  },
  {
    id: 'study-cards',
    name: 'StudyCards',
    badges: ['Full Stack', 'Vue', 'Nuxt', 'TypeScript', 'Material', 'NestJS', 'MongoDB', 'Mobile'],
    image: 'https://stuff.p-kin.com/pf-thumbs/studycards.jpg',
  },
  {
    id: 'games',
    name: '3D Games (Unity)',
    badges: ['Game', 'Unity', 'C#', 'Course contents'],
    image: 'https://stuff.p-kin.com/pf-thumbs/games/argonassault.jpg',
  },
  {
    id: 'startpage-v2',
    name: 'StartPage 2.0',
    badges: ['Angular', 'TypeScript', 'Firebase', 'AngularFire'],
    image: 'https://stuff.p-kin.com/pf-thumbs/startpage2.jpg',
  },
  {
    id: 'image-uploader',
    name: 'Image-Uploader Web Component',
    badges: ['TypeScript', 'Stencil JS', 'Web Component'],
    image: 'https://stuff.p-kin.com/pf-thumbs/image-uploader.jpg',
  },
  {
    id: 'firestore-db-admin',
    name: 'Firestore DB Admin page',
    badges: ['Angular', 'Material', 'TypeScript', 'Firebase', 'AngularFire'],
    image: 'https://stuff.p-kin.com/pf-thumbs/firestore-db-admin.jpg',
  },
  {
    id: 'pkincom-v2',
    name: 'P-Kin.com V2',
    badges: ['Vue', 'Vuex', 'TypeScript', 'SCSS', 'Firebase'],
    image: 'https://stuff.p-kin.com/pf-thumbs/pkincom-v2.jpg',
  },
  {
    id: 'web-dictionary',
    name: 'WebDictionary',
    badges: ['React', 'TypeScript', 'SCSS'],
    image: 'https://stuff.p-kin.com/pf-thumbs/webdict.jpg',
  },
  {
    id: 'autocomplete-react',
    name: 'Autocomplete - React component',
    badges: ['React', 'TypeScript', 'SCSS'],
    image: 'https://stuff.p-kin.com/pf-thumbs/autocomplete.jpg',
  },
  {
    id: 'mobile-friendly-notes',
    name: 'Mobile friendly Notes',
    badges: ['Svelte', 'SCSS', 'Firebase', 'Mobile'],
    image: 'https://stuff.p-kin.com/pf-thumbs/notes-mobile.jpg',
  },
  {
    id: 'startpage-v1',
    name: 'StartPage 1.0',
    badges: ['Bootstrap', 'JavaScript', 'JQuery', 'PHP', 'MySQL'],
    image: 'https://stuff.p-kin.com/pf-thumbs/startpage.jpg',
  },
  {
    id: 'pkincom-v1',
    name: 'P-Kin.com V1',
    badges: ['Bootstrap', 'JavaScript', 'JQuery', 'PHP', 'MySQL'],
    image: 'https://stuff.p-kin.com/pf-thumbs/pkincom-v1.jpg',
  },
];
