name: Code check and build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code_check:
    name: Code check and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.13.1

      - name: Install dependencies
        run: npm ci

      - name: Check code format
        run: npm run format:check

      - name: Lint all files
        run: npm run lint

      - name: Build app
        run: npm run build


